# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-03 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import user_form.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('booking_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('Booking_ref', models.CharField(default=user_form.models.rand_num, max_length=18, unique=True)),
            ],
        ),
    ]
